=== infsci2560sp16/full-stack-web-project-Seloen/src/main/resources/public/about.xsd
<?xml version="1.0"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
<!-- <xsd:element name="Branch"> -->
<xsd:element name="Movie">
<xsd:complexType>
<xsd:sequence>
<!-- <xsd:element name="Name" type="xsd:string"/>
<xsd:element name="Profession" type="xsd:string" />
<xsd:element name="Since" type="xsd:string"/>
<xsd:element name="Country" type="xsd:string"/>
<xsd:element name="State" type="xsd:string"/>
<xsd:element name="City" type="xsd:string"/>
<xsd:element name="OpenHour" type="xsd:string"/>
<xsd:element name="Phone" type="xsd:string"/>
<xsd:element name="Email" type="xsd:string"/>
<xsd:element name="Address" type="xsd:string"/> -->

<xsd:element name="Name" type="xsd:string"/>
<xsd:element name="Category" type="xsd:string" />
<xsd:element name="Year" type="xsd:string"/>
<xsd:element name="Country" type="xsd:string"/>
<xsd:element name="Director" type="xsd:string"/>
<xsd:element name="LeadingActor" type="xsd:string"/>
<xsd:element name="Duration" type="xsd:string"/>
<xsd:element name="Cost" type="xsd:string"/>
<xsd:element name="Profit" type="xsd:string"/>
<xsd:element name="Awards" type="xsd:string"/>

</xsd:sequence>
</xsd:complexType>
</xsd:element>
</xsd:schema>

=== infsci2560sp16/full-stack-web-project-Seloen/src/main/resources/public/about.xml
<?xml version="1.0" encoding="utf-8"?>
<Movie xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="about.xsd">


  <Name>Resident Evil</Name>
  <Category>Thrilling</Category>
  <Year>2000</Year>
  <Country>United States</Country>
  <Director>David</Director>
  <LeadingActor>Milla Jovovich</LeadingActor>
  <Duration>115 minutes</Duration>
  <Cost>1,000,000</Cost>
  <Profit>2,000,000</Profit>
  <Awards>none</Awards>

</Movie>
